# Generated by Django 4.0.2 on 2023-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='locationadd',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
